# Generated by Django 3.1.4 on 2020-12-18 11:08

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('alias_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('office_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('bill_sundry_decimal_places', models.IntegerField()),
                ('quantity_decimal_places', models.IntegerField()),
                ('currency_decimal_places', models.IntegerField()),
                ('search_vector', models.CharField(max_length=30)),
                ('date_format', models.IntegerField()),
                ('date_separator', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=300)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('mobile_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('password', models.CharField(max_length=15)),
                ('my_enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.enterprise')),
            ],
        ),
    ]
