# Generated by Django 3.1.4 on 2020-12-26 08:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('my_series', models.CharField(max_length=50)),
                ('due_date', models.DateField()),
                ('number', models.IntegerField()),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=50)),
                ('my_currency', models.CharField(max_length=50)),
                ('conversion_rate', models.DecimalField(decimal_places=5, max_digits=20)),
                ('gst_type_of_dealer', models.IntegerField()),
                ('gst_reverse_charge', models.BooleanField()),
                ('gst_ecomm_gstin', models.CharField(max_length=50)),
                ('gst_recepient_name', models.CharField(max_length=30)),
                ('gst_my_state', models.CharField(max_length=30)),
                ('gstin', models.CharField(max_length=50)),
                ('shipping_address', models.CharField(max_length=50)),
                ('billing_address', models.CharField(max_length=50)),
                ('gst_port_code', models.CharField(max_length=7)),
                ('gst_shipping_bill_number', models.IntegerField()),
                ('gst_shipping_bill_date', models.DateField()),
                ('gst_nature_of_document', models.IntegerField(choices=[(1, 'Sales'), (2, 'Sales Order'), (3, 'Sales Challan'), (4, 'Purchase'), (5, 'Purchase Order'), (6, 'Purchase Challan')])),
                ('gst_nature_of_transaction', models.IntegerField(choices=[(1, 'Sales Ttaxable'), (2, 'Sales Exempted'), (3, 'Sales Non Gst'), (4, 'Exports Exempted'), (5, 'Purchases Zero Rated'), (6, 'Imports Taxable')])),
                ('is_cancelled', models.BooleanField()),
                ('amount', models.DecimalField(decimal_places=5, max_digits=20)),
                ('party_bill_number', models.CharField(max_length=30)),
                ('party_bill_date', models.DateField()),
                ('tax_scope', models.IntegerField(choices=[(0, 'Exclusive Of Tax'), (1, 'Inclusive Of Tax'), (3, 'Out Of Scope')])),
                ('my_account', models.CharField(max_length=30)),
                ('my_center', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='VoucherItemRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('my_item', models.CharField(max_length=20)),
                ('my_umo', models.CharField(max_length=20)),
                ('quantity', models.CharField(max_length=40)),
                ('price', models.CharField(max_length=10)),
                ('lot_no', models.IntegerField()),
                ('description', models.CharField(max_length=50)),
                ('manufacturing_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=5, max_digits=20)),
                ('effective_amount', models.DecimalField(decimal_places=5, max_digits=20)),
                ('taxable_amount', models.DecimalField(decimal_places=5, max_digits=20)),
                ('final_amount', models.DecimalField(decimal_places=5, max_digits=20)),
                ('my_purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.purchase')),
            ],
        ),
        migrations.CreateModel(
            name='VoucherBillSundaryRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('my_bill_sundry', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=5, max_digits=20)),
                ('description', models.CharField(max_length=50)),
                ('my_voucher_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.voucheritemrow')),
            ],
        ),
        migrations.CreateModel(
            name='SubItemRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.CharField(max_length=30)),
                ('serial_number', models.IntegerField()),
                ('description', models.CharField(max_length=50)),
                ('my_voucher_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.voucheritemrow')),
            ],
        ),
    ]
