# Generated by Django 3.1.4 on 2020-12-30 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_purchase_subitemrow_voucherbillsundaryrow_voucheritemrow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subitemrow',
            name='my_voucher_item',
        ),
        migrations.RemoveField(
            model_name='voucherbillsundaryrow',
            name='my_voucher_item',
        ),
        migrations.RemoveField(
            model_name='voucheritemrow',
            name='my_purchase',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Enterprise',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='SubItemRow',
        ),
        migrations.DeleteModel(
            name='VoucherBillSundaryRow',
        ),
        migrations.DeleteModel(
            name='VoucherItemRow',
        ),
    ]
